# 项目相关配置
mproject:
  # 名称
  name: MProject
  # 版本
  version: 1.1
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/mproject/uploadPath，Linux配置 /home/mproject/uploadPath）
  profile: D:/mproject/uploadPath
  
  # 获取ip地址开关
  addressEnabled: true

  staticUploadPrefix: /static/upload/

  staticUpload: /static/upload/**

  uploadFolderPath: D:/mproject/static/upload/

  imgServer: http://localhost:8888/teamProject/
  
  #用户默认图标
  userImg: user.jpg
  #项目默认图标
  projectImg: project.png

  downloadServer: http://localhost:8888
   
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8888
#  servlet:
#    # 应用的访问路径
#    context-path: /api/
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: debug

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
      
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&tinyInt1isBit=false
      username: root
      password: root123456
  #Redis
  redis:
    # 地址
    host: 192.168.0.200
    # 端口，默认为6379
    port: 6379
    # 密码
    password: 1qaz2wsx
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


  